package com.project.chamjimayo.controller.dto;

import lombok.Getter;

@Getter
public enum ErrorCode {
  //400 BAD_REQUEST 잘못된 요청
  INVALID_PARAMETER,
  NEED_MORE_PARAMETER,
  USER_DUPLICATE_EXCEPTION,
  USER_NICK_NAME_DUPLICATE_EXCEPTION,
  AUTH_EXCEPTION,
  INVALID_TOKEN_EXCEPTION,
  USER_NOT_FOUND_EXCEPTION,
  METHOD_ARGUMENT_NOT_VALID_EXCEPTION,

  // 401 Unauthorized 인증되지 않음


  // 403 Forbidden 권한 없음


  //404 NOT_FOUND 잘못된 리소스 접근
  SEARCH_NOT_FOUND,
  API_NOT_FOUND,
  JSON_NOT_FOUND,

  // 405 METHOD_NOT_ALLOWED 지원되지 않는 HTTP 요청 메서드
  INVALID_HTTP_METHOD,

  //500 INTERNAL SERVER ERROR 서버 오류
  DATABASE_ERROR,
  INTERNAL_SERVER_ERROR
}
