package com.project.chamjimayo.controller.dto;

public enum ErrorCode {
  AUTH_EXCEPTION,
  INVALID_TOKEN_EXCEPTION,
  USER_DUPLICATE_EXCEPTION,
  USER_NICK_NAME_DUPLICATE_EXCEPTION,
  USER_NOT_FOUND_EXCEPTION,
  METHOD_ARGUMENT_NOT_VALID_EXCEPTION,
  RESTROOM_NAME_DUPLICATE_EXCEPTION,
  DATABASE_EXCEPTION,
  FILE_NOT_FOUND,
  IOEXCEPTION
}
